### PR TITLE
pass gridcell averaged albedo from all_vars struct to wrf

### PR DESCRIPTION
**Pull request by dgergel**
- [ ] ~~closes #xxx~~
- [x] tests passed
- [ ] ~~new tests added~~
- [ ] ~~science test figures~~
- [x] ran uncrustify prior to final commit
- [X] ReleaseNotes entry

This quick PR is a follow-up to #712 and #710 so that the `cesm_put_data.c` routine in the CESM driver passes gridcell-averaged albedo to WRF.

### CODE REVIEW

**Comment by dgergel** [comment]
We should hold off on merging this until I address the issue that @bartnijssen and I were looking at yesterday (we need to be passing veg or snow albedos when shortwave is zero). I am going to see if I can do this before I leave tomorrow for vacation.

**Comment by dgergel** [comment]
@jhamman and @bartnijssen this is ready for another review.

**Comment by jhamman** [comment]
@dgergel - can you post a few figures that demonstrate the behavior of this version of the code?

**Comment by dgergel** [comment]
@jhamman I've just posted a bunch of figures in the RASM slack channel showing this.

**Comment by dgergel** [comment]
Some figures that demonstrate the behavior of this version of the code (note that this PR includes changes to both cold start albedo and how we're calculating albedo at each time step, so I'm including figures for both):

First timestep (colorbar ranges not set so that the full ranges are clear):
VIC4 
image

VIC5
image

Second timestep (VIC5 colorbar set to VIC 4 colorbar min and max):
image

Third timestep:
image

**Comment by dgergel** [comment]
@jhamman all done. This should be ready to merge.

**Pull request merged**
