### PR TITLE
Fix time precision issue for long VIC runs

### PR DESCRIPTION
**Pull request by yixinmao**
Before this fix, the timestamps of long VIC runs were incorrect in some cases. This PR is in response to issue #663.

**Reason**: The reason  of this issue is that during the step where timestamps are made (in `make_dmy`), the length of a timestep is first converted into the specified time unit, denoted as `dt_time_units`; then a series of timestamps for the whole running period is determined by incrementally increase the timestamp by `dt_time_units`. When `dt_time_units` is not precise, the incremented timestamp will accumulate the small error of `dt_time_units`, potentially resulting in incorrect timestamp after a long simulation time.

**Example**: for example, say the time unit is day, and the model timestep is hourly. In this case, `dt_time_units = 1/24`, which is stored as a finite number in the computer with a very small cut-off error. The accumulated error due to this results in an incorrect timestamp shift after ~14 years, and eventually terminates model outputs afeter ~31 years.

**Solution**: when generating the timestamp for each timestep, calculate the accumulating time length from the simulating start time precisely, then store the time. In this way, there is only one cut-off error ofr all timestamps without error accumulation.

### CODE REVIEW

**Comment by yixinmao** [comment]
@tbohn , could you take a look at this PR? If you are able to use the new code to test on your data that originally caused error, that'd be great. Thanks!

**Comment by bartnijssen** [comment]
@jhamman : Could you take a quick look at this on travis? The build is failing because of an HDF library issue (is this the same problem someone else mentioned in the past week - it vaguely rings a bell).

**Comment by jhamman** [comment]
The failing tests are all due to an issue with Anaconda, not VIC. I'll look into why this is happening. @yixinmao - did the test suite pass locally?

**Comment by tbohn** [comment]
@yixinmao sure, I'm testing it out now.

**Comment by jhamman** [comment]
@yixinmao - can we get a what's new note?

**Comment by yixinmao** [comment]
@jhamman I'm running the tests locally now (I haven't run the test locally for a while so ran into some issues that are probably not due to this PR...). Do you mean a release note?

**Comment by jhamman** [comment]
yes, a release note.

**Comment by tbohn** [comment]
@yixinmao The code works correctly for me now.  Thanks!

**Comment by bartnijssen** [comment]
Can be merged after travis build passes (issue 669)

**Pull request merged**
