### PR TITLE
Feature/cesm timingtables secsday columns

### LINKED ISSUE #745: fix sec/day columns in vic timing tables in CESM driver
Currently the `secs/day` columns in the VIC timing tables in the CESM driver are not being populated correctly because several of the fields in the `global_param` struct that we populate in image mode do not get populated in the CESM driver, including `nrecs`, `endyear`, `endmonth` and `endday`. 

Here is an example timing table from a 5-day RI run: 

```
------------------------------ VIC TIMING PROFILE ------------------------------

  Date                      : Thu Aug 31 20:45:49 2017
  Compiler                  : icc (Intel(R) C++ gcc 4.3 mode)
  Machine                   : r2i4n15
  VIC User                  : gergel
  VIC Version               : unset
  VIC GIT Version           : 5.0.1 February 1, 2017
  VIC_DRIVER                : CESM

  Global Param File         : vic.globalconfig.txt
  Domain File               : /p/work2/projects/rasm/inputdata/share/domains/domain.lnd.wr50a_ar9v4.100920.nc
  Start Date                : 1948-09-01-00000
  Stop Date                 : 0000-00-00
  Nrecs                     : 1
  Model Timestep (seconds)  : 3600
  Snow Timestep (seconds)   : 3600
  Runoff Timestep (seconds) : 3600
  Atmos Timestep (seconds)  : 3600

  MPI Processes             : 64
  OPENMP Threads            : 1
  Total pes active          : 64
  pes per node              : 72

  Overall Metrics
  ---------------
    Model Cost       : 288181 pe-hrs/simulated_year
    Model Throughput : 0.00532998 simulated_years/day

  Timing Table:
|------------|----------------------|----------------------|----------------------|----------------------|
| Timer      | Wall Time (secs)     | CPU Time (secs)      | Wall Time (secs/day) | CPU Time (secs/day)  |
|------------|----------------------|----------------------|----------------------|----------------------|
| Init Time  |              1.61307 |                 0.52 |              38.7138 |                12.48 |
| Run Time   |              14.0763 |                13.43 |              337.831 |               322.32 |
| Final Time |            0.0151892 |                 0.02 |              0.36454 |                 0.48 |
| Total Time |              1850.48 |              1847.55 |              44411.5 |              44341.2 |
|------------|----------------------|----------------------|----------------------|----------------------|
| Force Time |              0.15157 |                 0.17 |              3.63768 |                 4.08 |
| Write Time |              470.351 |               470.02 |              11288.4 |              11280.5 |
|------------|----------------------|----------------------|----------------------|----------------------|


------------------------------ END VIC TIMING PROFILE ------------------------------
```

### PR DESCRIPTION
**Pull request by dgergel**
- [X] closes #745 
- [x] tests passed
- [ ] ~new tests added~
- [ ] ~science test figures~
- [X] ran uncrustify prior to final commit
- [X] ReleaseNotes entry

### CODE REVIEW

**Comment by bartnijssen** [comment]
@dgergel : Please resolve merge conflict

**Comment by dgergel** [comment]
An timing table with this branch from a 5-day RI run: 

```
------------------------------ VIC TIMING PROFILE ------------------------------

  Date                      : Fri Sep  1 20:44:48 2017
  Compiler                  : icc (Intel(R) C++ gcc 4.3 mode)
  Machine                   : r8i4n0
  VIC User                  : gergel
  VIC Version               : unset
  VIC GIT Version           : 5.0.1 February 1, 2017
  VIC_DRIVER                : CESM

  Global Param File         : vic.globalconfig.txt
  Domain File               : /p/work2/projects/rasm/inputdata/share/domains/domain.lnd.wr50a_ar9v4.100920.nc
  Start Date                : 1948-09-01-00000
  Stop Date                 : 1948-09-06
  Nrecs                     : 120
  Model Timestep (seconds)  : 3600
  Snow Timestep (seconds)   : 3600
  Runoff Timestep (seconds) : 3600
  Atmos Timestep (seconds)  : 3600

  MPI Processes             : 64
  OPENMP Threads            : 1
  Total pes active          : 64
  pes per node              : 72

  Overall Metrics
  ---------------
    Model Cost       : 2401.31 pe-hrs/simulated_year
    Model Throughput : 0.639651 simulated_years/day

  Timing Table:
|------------|----------------------|----------------------|----------------------|----------------------|
| Timer      | Wall Time (secs)     | CPU Time (secs)      | Wall Time (secs/day) | CPU Time (secs/day)  |
|------------|----------------------|----------------------|----------------------|----------------------|
| Init Time  |              1.12486 |                 0.52 |             0.224971 |                0.104 |
| Run Time   |              1849.18 |              1846.94 |              369.835 |              369.388 |
| Final Time |            0.0232549 |                 0.01 |           0.00465097 |                0.002 |
| Total Time |              1850.32 |              1847.47 |              370.065 |              369.494 |
|------------|----------------------|----------------------|----------------------|----------------------|
| Force Time |             0.151743 |                 0.22 |            0.0303486 |                0.044 |
| Write Time |              470.239 |               469.86 |              94.0478 |               93.972 |
|------------|----------------------|----------------------|----------------------|----------------------|


------------------------------ END VIC TIMING PROFILE ------------------------------
```

**Comment by bartnijssen** [comment]
Thanks for the timing table. @dgergel : Once you resolve the merge conflict I'll go ahead and merge the PR (it's a simple conflict in the release notes

**Comment by dgergel** [comment]
@bartnijssen already resolved it (see above commit)

**Pull request merged**
