### PR TITLE
Fix the bug of  #455

### PR DESCRIPTION
**Pull request by pengbinpeluo**
Hi Joe and Ted, 
This pull request is for #455.
Cheers!
Bin.

### CODE REVIEW

**Comment by jhamman** [comment]
@tbohn - what do you think?

**Comment by tbohn** [comment]
This looks good to me.  Thanks for fixing this, @pengbinpeluo

**Comment by pengbinpeluo** [comment]
Cheers! @jhamman  @tbohn

**Comment by jhamman** [comment]
Thanks @pengbinpeluo - This will go out in 4.2.d and will be released when we release VIC 5 in about a month or so.

**Pull request merged**
