### PR TITLE
Added support for reading blowing snow parameters in image driver

### LINKED ISSUE #327: Implement reading of blowing snow parameters in 5.0 image mode
Currently vic_init() just contains a placeholder for reading blowing snow parameters.

### PR DESCRIPTION
**Pull request by tbohn**
This closes #327.

This is a branch off of PR #388.  Thus at present it contains the commits from that PR.  But as soon as that PR is taken, the diff for this PR should collapse down to a single file: vic/drivers/image/src/vic_init.c.

### CODE REVIEW

**Comment by tbohn** [comment]
Rebased this branch against my PR for lake parameter support.

**Comment by jhamman** [comment]
@tbohn - it doesn't seem like your rebase did anything.  In fact, it may have made things worse.  I'm still getting the full diff from #388.

**Comment by tbohn** [comment]
Haven't rebased yet due to dew being down (as I mentioned in my other
email).  I'll let you know when it's ready.

**Comment by tbohn** [comment]
Rebased against develop, which now incorporates the previous PR.

**Comment by jhamman** [comment]
Looks good.  Thanks @tbohn.  Merging now...

**Pull request merged**
