### PR TITLE
Changes discussed in #790

### PR DESCRIPTION
**Pull request by Sibada**
- [ ] closes #xxx
- [ ] tests passed
- [ ] new tests added
- [ ] science test figures
- [ ] ran uncrustify prior to final commit
- [ ] ReleaseNotes entry

There are failure in the unit test:
```bash
=================================== FAILURES ===================================
_________________________________ test_strpdmy _________________________________
def test_strpdmy():
        dmy = ffi.new("dmy_struct *")
    
        dates = pd.date_range('2015-12-18', '2016-12-22', freq='1D')
        date_format = '%Y-%m-%d'
        for date in dates:
            date_str = date.strftime(date_format)
            vic_lib.strpdmy(date_str.encode(), date_format.encode(), dmy)
>           expected = date.to_datetime()
E           AttributeError: 'Timestamp' object has no attribute 'to_datetime'
tests/unit/shared/test_vic_time.py:374: AttributeError
========== 1 failed, 55 passed, 16 skipped, 1 xpassed in 4.80 seconds ==========
```
But the tests of examples seem no failure. Might it because of my changes?

### CODE REVIEW

**Comment by jhamman** [comment]
@Sibada - We're seeing a bunch of test failures here with the following message: 

> cffi.error.FFIError: multiple declarations of variable LOG_DEST (for interactive usage, try cdef(xx, override=True))

Any thoughts on how to fix this?

**Comment by jhamman** [comment]
To answer your above question, the tests are passing on develop so yes, I suspect your changes are responsible for the failures.

**Comment by jhamman** [comment]
@Sibada - the 'Timestamp failure has been fixed in develop. There are still failures here to address. 

Something you may consider doing is enabling a c++ build of VIC on Travis and maybe even setting up Appveyor to test VIC using Windows. I think those changes are the logical first steps in supporting C++/windows with VIC. 

Travis C++: https://docs.travis-ci.com/user/languages/cpp/
Appveyor C++: https://www.appveyor.com/docs/lang/cpp/

**Comment by Sibada** [comment]
Feel sorry for no replying for these days because I'm busy for revise of my paper and development of the R package. The package finally can run on my win7 platform computer.
Might `multiple declarations of variable LOG_DEST` is because no `extern` in some source files?

**Comment by Sibada** [comment]
I'm sorry for my no replying because I'm busy in revising my paper and development of the R package. It seems successfully compiled and run on my R platform on my win7 computer.

**Comment by Sibada** [comment]
After the development of the R package, I found that little modification of VIC source code such as in this puul request make little sense because of large difference between the raw terminal environment of os and the R runtime environment. For example, in the original VIC source code `exit()` is used to stop the running when error occurs but when it is used in R, it would terminate the entire R process and might cause irretrievable losses, therefore a specific exit function for R are expected. Several places of the original source code are also needs to be modified when adopted to R due to the strict policy of CRAN. In fact, to pass the R CMD check (determined whether this R package could be technologically accepted by CRAN), the original VIC source code I placed in the R package have been beyond recogniton.

**Comment by Sibada** [comment]
@jhamman
In my view, it might be less worthy to make individual drivers use their own exit functions. To realize that we can move the definition of `log_err()` and `log_warn()` to a source file determined each drivers but it would cause higher coupling between the modules.
I also found that the R environment also needs specified print function. The original `printf()` of C also can work in R environment but CRAN could not accept it. In fact I could not exactly remember what I have done in the VIC source codes...
However I have some suggestions for the VIC source codes and it might be useful:
I found that the codes that check or transform the parameters after they're read in (e.g. those calculate soil properties,  critical and wilting point moisture contents of soil after the parameters have been get from file and assigned to the soil_con struct) are usually just placed after the codes that read the parameters, and they are repetitively in different drivers (classic and image). I thought it might be more proper to set them as a single function in the share_all module and it can be used by several drivers.
In some functions that transform parameter from string type to enum (e.g. str_to_XXX), the arguement of the input string (`char* xxx`) might be better to use (`const char* xxx`). The string objects of C++ can provide their char* but it is const.

My package have not upload to CRAN yet because I have to deal with how to pass the R CMD Check. For linux platform there are no ERROR and WARNING but some WARNINGs exist in windows platform.
Can you have a try to this package and give some suggestions? I place it in a China netdisk because most US netdisks are blocked by the GFW.
https://pan.baidu.com/s/10N6gcbzU6DyoAyK_Wmytew
And can I use your STEHE dataset as sample dataset for this package?

**Comment by jhamman** [comment]
@Sibada - thank you for your detailed response. Happy to keep this closed and we can revisit down the road if/when others are interested.

**Pull request closed without merging**
