### PR TITLE
Fixed a unit conversion bug - snow depth, density and SWE

### PR DESCRIPTION
**Pull request by yixinmao**
Fixed a unit conversion bug in vic_run, related to calculating snow depth from snow density and SWE

### CODE REVIEW

**Comment by yixinmao** [comment]
Currently the travis testing is failing when using clang, due to this travis issue: https://github.com/travis-ci/travis-ci/issues/6120

**Comment by yixinmao** [comment]
The relationship between snow water equivalent, snow density and snow depth is:
    depth [m] = 1000 * SWE [m] / density [kg/m3]
where the constant 1000 is the density of water (in kg/m3), not MM_PER_M. This PR corrected this constant.

**Comment by jhamman** [comment]
@yixinmao - Can you either:

1.  Move the failing Clang test to the list of expected failures in `.travis.yml`, or
2.  Try to follow the install steps shown to fix https://github.com/travis-ci/travis-ci/issues/6120.

**Comment by yixinmao** [comment]
@jhamman done - have moved the test to allowed failure

**Pull request merged**
