### PR TITLE
Commit to fix memory error in get_nc_var_text

### PR DESCRIPTION
**Pull request by bartnijssen**
@jhamman: I think this is the fix that is needed. This is just for review

Let me know how to squash all these "merge" commits.

### CODE REVIEW

**Comment by jhamman** [comment]
cc @wietsefranssen - this should fix the bug you were seeing.

**Comment by jhamman** [comment]
@bartnijssen - I think we should just go ahead and merge this as is. A rebase/squash isn't going to get rid of these commits since they are already (most of them at least) in the develop branch.  I'm honestly not sure why they are showing up here.

**Comment by jhamman** [comment]
thanks @bartnijssen.

**Comment by wietsefranssen** [comment]
Thanks! It indeed solved the error!

**Pull request merged**
