### PR TITLE
Update image driver docs - `run_cell` not used in param file, removed from the docs

### PR DESCRIPTION
**Pull request by yixinmao**
This PR will close issue #649

### CODE REVIEW

**Comment by bartnijssen** [comment]
I don't understand the change - wouldn't the proper fix be to use `run_cell` to determine whether a cell is run or not?

**Comment by yixinmao** [comment]
@bartnijssen : right now there are two places that could specify whether a cell is run or not - `mask` variable in the input domain file, and `run_cell` variable in the parameter file. Currently in the code, we are only using `mask` to determine if a cell is run or not, and `run_cell` is not used at all. And I think it makes sense to run the cells based on the domain file, that's why I made the change, since the current documentation is misleading.

But another way to do it is we completely use `run_cell` to control running a cell or not. I guess the benefit of doing so is that if the user has a large domain (thus the 'mask' variable), but s/he wants to turn some grid cells on and off, s/he can adjust `run_cell` in the parameter file to do so rather than changing the `mask` variable in the domain file. If this way is preferred, we can make code changes to achieve so.

**Comment by bartnijssen** [comment]
To me these two things signify something different. 

`mask` in the domain file simply designates all the cells that are part of a model domain. For example, for RASM this domain never changes. 
`run_cell` makes it clear which cells in the domain should actually be simulated.

This is not the same thing. We are in the habit of having masks that match exactly with the information that we have in other fields (so all fields outside the mask are `Fill_Value`), but that just happens to be the way in which we implement most of our simulations. In that case a separate `mask` is not necessary. But I can imagine cases in which you have values over the entire domain (in the input fields), in which case you cannot easily reconstruct the `mask` if you just want to run over a small subset, which is why we have `run_cell`.

So the solution proposed here is not the one I want us to use. We should use `run_cell` in the code to determine whether a cell needs to be run, not `mask`.

**Comment by bartnijssen** [comment]
Given the above I am closing the PR. Fixing it the other way (and use `run_cell`) should be an easy fix as well.

**Comment by bartnijssen** [comment]
It's fine with me if we add `run_cell` to the domain file as part of this (not sure where it currently lives).

**Comment by yixinmao** [comment]
@bartnijssen OK that makes sense. I do agree that the second way is more reasonable and flexible for users. I'll make the changes later.

**Pull request closed without merging**
