### PR TITLE
VIC website hosted on Read-the-docs

### LINKED ISSUE #155: Use MkDocs to generate VIC website?
I'd like to propose using [Sphinx](http://sphinx-doc.org/) to generate the VIC website.  The main reasons I think it would be a good idea are:

- Easily versionable - users could select between version of documentation (4.1.2, 4.2, 5.0, etc.)
- Development is done outside of production area
- Supports deployment webhooks with git (e.g. [read-the-docs](http://read-the-docs.readthedocs.org/en/latest/index.html))
- Uses reStructuredText markdown styles - markdown styles are easier to write in, less brittle, etc.
- Customizable html styles - we could use the same css styles we currently use

Of course this would take a bit of work but there is a converter that converts existing html to reStructuredText.  Beyond that, there are just some setup tasks that may take a day or so.  

Thoughts?

Related #154 ...

### LINKED ISSUE #176: Make VIC code citable?
How do we want the VIC model to be cited?

Is citing the [*Primary Historical Reference*: Liang et al. (1994)](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/References.shtml#VIC) sufficient?  Obviously, there have been many changes to the VIC model since 1994.

I've recently run across Github's page on [Making your code citable](https://guides.github.com/activities/citable-code/) and thought I would bring it up here to see if anyone had thoughts.  In short, we have the option of tying a particular [DOI](http://en.wikipedia.org/wiki/Digital_object_identifier) to the model source code itself, allowing individual releases to be directly citable.  Below is a list of links that outline how this can be done:
- [Github: Making your code citable](https://guides.github.com/activities/citable-code/)
- [Mozilla Science Lab](http://mozillascience.org)
  - [Introduction](http://mozillascience.org/code-as-a-research-object-a-new-project/)
  - [Code as a Research Object](http://mozillascience.github.io/code-research-object/)
- [Zendo](https://zenodo.org/):  "Zenodo is an open dependable home for the long-tail of science, enabling researchers to share and preserve any research outputs in any size, any format and from any science."
- [Figshare](http://figshare.com/):  "figshare is a repository where users can make all of their research outputs available in a citable, shareable and discoverable manner."

### LINKED ISSUE #236: fix internal page hyperlinks in docs
`mkdocs` does internal page hyperlinks a bit different that the html-to-markdown converter does.  This has resulted in a bunch of broken hyperlinks in the new docs.  

An example: http://vic.readthedocs.org/en/latest/Documentation/Calibration/#RoutCal

### PR DESCRIPTION
**Pull request by jhamman**
Live version of docs is here: http://vic.readthedocs.org/en/latest/

TODO:

- [x] Grant admin rights of read the docs to @bartnijssen 
- [x] Fix broken links
- [x] Fix missing figures
- [x] Use `mkdocs.yml` `pages` feature to sort pages and sections in sidebar
- [x] Configure hidden pages (issue raised here: https://github.com/mkdocs/mkdocs/issues/699)
- [x] Add zenodo badge
- [x] Link with Github so docs are automatically built after push
- [x] Link with Google Analytics 
- [x] Fix broken internal page hyperlinks

closes #155 
closes #176
closes #236

### CODE REVIEW

**Comment by bartnijssen** [comment]
I signed up for readthedocs

**Comment by jhamman** [comment]
Great.  You have been added as a maintainer.

**Comment by jhamman** [comment]
@bartnijssen - This is basically done.  A few minor details to work through. How do we want to do a code review on this?  I'm thinking a few sets of eyes (other than mine) on the built docs themselves would be best.

**Comment by jhamman** [comment]
@tbohn - Would you be able to review this PR?  Once we merge this, we'll redirect http://www.hydro.washington.edu/Lettenmaier/Models/VIC/ to the read the docs site.

Mostly looking over the docs and reporting anything that isn't looking right. This should include almost all of the current docs from our website except for those that I couldn't justify moving over.

**Comment by tbohn** [comment]
OK, I'll try to do this today.

**Comment by tbohn** [comment]
It's going to take a little longer, unfortunately.  I will try to do it
tomorrow.
Ted

**Comment by tbohn** [comment]
OK, this looks good, with just a couple of minor issues:
1. "Model Overview" subsection "Land Cover and Soil" originally had 2 subsubsections ("land cover" and "soil").  Somehow in the new version, the "soil" subsubsection got promoted to subsection at the same level as "Land Cover and Soil", resulting in "Soil" having its own entry in the left-hand menu and looking a little redundant.
2. "Model Overview" subsection "Snow Model": the first line of text appears twice
3. "Model Overview" subsection "Frozen Soil": this says that explicit and linear are the default - didn't we change the default to implicit and exponential?  This isn't really an error in your transfer to GIT (it is the same as the old version), but it might be worth correcting.
4. "Documentation" subsections "VIC Modes of Operation" and "Archived Notes": none of the pages linked under here retained their figures; and the link to the page "VIC/GOES radiation evaluation" is broken.
5. "Documentation" subsection "Running VIC" has a subsubsection "Code Source Code" - I think this should be "Source Code".

There are a number of other things I've noticed that aren't errors in transfer but are things that should be updated/corrected.  I assume I can update these after you do this pull request?

Cheers,
Ted

**Comment by bartnijssen** [comment]
@tbohn: Yes - we can update after we make sure the current transfer is correct (same as old web site).
@jhamman: Once you've incorporated Ted's changes and resolved the conflicts let me know and I'll read through as well before merging the PR

**Comment by jhamman** [comment]
Thanks @tbohn, I'll take care of these remaining issues in the morning.

**Comment by jhamman** [comment]
@bartnijssen - ready for your eyes now.

**Comment by jhamman** [comment]
will also update `master`.

**Pull request merged**
